### ISSUE TITLE
Setup sign_up_status for users

### ISSUE THREAD

**Issue by WrnerM** [danjvarela/baynans#29]

**Comment by danjvarela** [comment]
- Create a migration to add sign_up_status to users table. Default value should be 0. Should be integer type.
  - On the user model, create enum for sign_up_status. Possible values are :pending, :approved
  - Using callbacks, set `sign_up_status` to `:pending` if `user_type` is `:trader` before validation
  - Using callbacks, set `sign_up_status` to `:approved` if `user_type` is `:admin` before validation
  - Reset database

**Comment by danjvarela** [comment]
# Important Changes

- Instead of `sign_up_status`, we'll choose `trading_status` so it is not confused with the user's sign up status (whether they are confirmed or not).
